apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-pr-testing
  namespace: openshift-gitops
spec:
  generators:
  - pullRequest:
      github:
        owner: lordofthejars
        repo: bgd-pr
        labels:
        - preview
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'bgd-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/lordofthejars/bgd-pr'
        targetRevision: '{{head_sha}}'
        path: app/overlays/default/
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'bgd-{{branch}}-{{number}}'
